// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import NextTopLoader from "nextjs-toploader";
// import TopNavbar from "@/components/navbar/TopNavbar";
// import Navbar from "@/components/navbar/Navbar";
// import Footer from "@/components/footer/Footer";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <TopNavbar />
//         <Navbar />
//         <main className="relative overflow-hidden">
//           <NextTopLoader color="#FF0000" height={5} />
//           {children}
//         </main>
//         <Footer />
//         </body>
//     </html>
//   );
// }

// RootLayout.tsx

// app/layout.tsx
import { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";
import TopNavbar from "@/components/navbar/TopNavbar";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { AuthProvider } from "@/providers/AuthProvider";
import { SiteProfileProvider } from "@/context/SiteProfileContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <SiteProfileProvider>
            <TopNavbar />
            <Navbar />
            <main className="relative overflow-hidden">
              <NextTopLoader color="#FF0000" height={5} />
              {children}
            </main>
            <Footer />
          </SiteProfileProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
